language: node_js
node_js:
  - "node"
  - "iojs"
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/0c874b440b04132ffb9f # gitter: gaintext
      - https://webhooks.gitter.im/e/b4a45e9dcf37c00604f8 # gitter: gaintext/gaintext.js
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
